import { MenuItem, GalleryItem, Testimonial } from './types';

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 's1',
    name: 'Chicken 65 (Bone)',
    description: 'Tender chicken pieces (with bone) marinated in signature Southern spice blends and crisp-fried to juicy perfection.',
    price: 130,
    category: 'starters',
    isVeg: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 's2',
    name: 'Chicken 65 (Boneless)',
    description: 'Crispy and succulent boneless chicken chunks marinated with aromatic Southern spices, fresh ginger-garlic paste, and curry leaves.',
    price: 180,
    category: 'starters',
    isVeg: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 's3',
    name: 'Chicken Lollipop Dry',
    description: 'Delectably seasoned local chicken drummettes fried to golden-brown crispiness and served dry with customized Indian spices.',
    price: 140,
    category: 'starters',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 's4',
    name: 'Chicken Lollipop Saucy',
    description: 'Crispy glazed chicken drummettes coated in a highly secret, spicy, sweet, and tangy chef\'s special sauce.',
    price: 170,
    category: 'starters',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 's5',
    name: 'Only 65',
    description: 'Our signature ultra-crispy bites heavily spiced with premium, house-ground local 65 seasoning.',
    price: 120,
    category: 'starters',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 's6',
    name: 'Gobi 65',
    description: 'Crunchy farm-fresh cauliflower florets dipped in deep-spiced rice batter and golden fried.',
    price: 110,
    category: 'starters',
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 's7',
    name: 'Paneer 65',
    description: 'Gently marinated premium cottage cheese cubes tossed in spicy Southern herbs and deep fried.',
    price: 140,
    category: 'starters',
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 's8',
    name: 'Mushroom 65',
    description: 'Succulent organic button mushrooms coated in legendary spices and fried to crunchy perfection.',
    price: 130,
    category: 'starters',
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?q=80&w=600&auto=format&fit=crop',
  },
  
  // Category 2: Chicken Gravy / Dry
  {
    id: 'c1',
    name: 'Chilli Chicken Dry',
    description: 'Tender crispy chicken chunks tossed in a savory, spicy, and tangy chili-soy sauce with fresh peppers.',
    price: 150,
    category: 'chicken',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'c2',
    name: 'Chilli Chicken Gravy',
    description: 'Delectable battered chicken bites simmered in a rich, spicy, and tangy Indo-Chinese dark chili gravy.',
    price: 170,
    category: 'chicken',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'c3',
    name: 'Chicken Manchurian Dry',
    description: 'Crispy chicken bits tossed with finely chopped garlic, ginger, green chilies, and tangy Manchurian glaze.',
    price: 160,
    category: 'chicken',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'c4',
    name: 'Chicken Manchurian Gravy',
    description: 'Juicy chicken chunks cooked in a succulent, velvety ginger-garlic Manchurian sauce.',
    price: 180,
    category: 'chicken',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'c5',
    name: 'Chicken Masala',
    description: 'Traditional home-style chicken curry slow-cooked with fresh tomatoes, onions, and freshly ground country spices.',
    price: 160,
    category: 'chicken',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'c6',
    name: 'Only Chicken Masala',
    description: 'An intense, extra-thick rich chicken gravy made with our secret spice paste, cooked slowly for deep flavor.',
    price: 170,
    category: 'chicken',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'c7',
    name: 'Pepper Chicken Masala',
    description: 'A fiery, semi-dry preparation featuring tender chicken tossed with abundance of freshly cracked black pepper and curry leaves.',
    price: 170,
    category: 'chicken',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'c8',
    name: 'Chettinadu Chicken Masala',
    description: 'An aromatic, legendary South Indian classic cooked with roasted coconut, fennel, star anise, and signature Chettinad spices.',
    price: 180,
    category: 'chicken',
    isVeg: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'c9',
    name: 'Chicken Fry',
    description: 'Deep-marinated country chicken pieces wok-tossed with aromatic spices and caramelized curry leaves.',
    price: 170,
    category: 'chicken',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'c10',
    name: 'Butter Chicken Masala',
    description: 'Rich, velvety, and mildly sweet tomato-cashew cream gravy loaded with succulent roasted chicken tikka pieces.',
    price: 190,
    category: 'chicken',
    isVeg: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=600&auto=format&fit=crop',
  },
  // Category 3: Mutton Gravy / Dry
  {
    id: 'm1',
    name: 'Mutton Masala',
    description: 'Tender goat meat slow-cooked in a traditional rich onion-tomato gravy with house-ground spices.',
    price: 220,
    category: 'mutton',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'm2',
    name: 'Chettinadu Mutton Masala',
    description: 'Fiery and aromatic South Indian classic featuring tender mutton simmered in a freshly roasted coconut and Chettinad spice paste.',
    price: 230,
    category: 'mutton',
    isVeg: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'm3',
    name: 'Mutton Fry',
    description: 'Succulent mutton chunks pan-fried with caramelised onions, green chilies, and handpicked local spices.',
    price: 200,
    category: 'mutton',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'm4',
    name: 'Mutton Pepper Fry',
    description: 'A spicy dry preparation of tender mutton tossed with an abundance of freshly crushed black pepper and fresh curry leaves.',
    price: 220,
    category: 'mutton',
    isVeg: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'm5',
    name: 'Prawns Masala',
    description: 'Juicy fresh prawns cooked in a semi-dry, flavorful tomato and spice masala.',
    price: 180,
    category: 'mutton',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1559737632-23f2f89ca92e?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'm6',
    name: 'Chettinadu Prawns Masala',
    description: 'Plump prawns cooked in a traditional fiery Chettinad gravy with roasted coconut and regional herbs.',
    price: 190,
    category: 'mutton',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'm7',
    name: 'Fish Masala',
    description: 'Fresh fish fillets gently simmered in a tangy, spiced tamarind and coconut curry.',
    price: 210,
    category: 'mutton',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'm8',
    name: 'Kadai Chicken',
    description: 'Tender chicken pieces wok-tossed with bell peppers, onions, tomatoes, and coarsely ground Kadai spices.',
    price: 180,
    category: 'mutton',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'm9',
    name: 'Mutton Thala Curry',
    description: 'A rustic, highly traditional country-style goat head curry cooked with aromatic regional spices.',
    price: 140,
    category: 'mutton',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'm10',
    name: 'Mutton Boti',
    description: 'Spicy and flavorful goat tripe dry-cooked with ginger-garlic, curry leaves, and Southern masalas.',
    price: 120,
    category: 'mutton',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'm11',
    name: 'Mutton Payya',
    description: 'Slow-simmered rich and gelatinous goat trotters soup cooked overnight with traditional spices.',
    price: 130,
    category: 'mutton',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=600&auto=format&fit=crop',
  },
  // Category 4: Parotta & Chapatti
  {
    id: 'p1',
    name: 'Parotta (1 Piece)',
    description: 'Multi-layered, flaky, golden-brown flatbread cooked on a hot griddle.',
    price: 20,
    category: 'parotta',
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'p2',
    name: 'Veechu Parotta',
    description: 'Thin, expertly stretched layered flatbread folded into an elegant square shape.',
    price: 25,
    category: 'parotta',
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'p3',
    name: 'Ceylon Parotta',
    description: 'Soft, layered stuffed flatbread folded and cooked to a golden crispy finish.',
    price: 100,
    category: 'parotta',
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'p4',
    name: 'Chicken Ceylon Parotta',
    description: 'Savory layered flatbread stuffed with perfectly spiced minced chicken, egg, and fresh regional herbs.',
    price: 140,
    category: 'parotta',
    isVeg: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'p5',
    name: 'Egg Lappa',
    description: 'A classic South Indian street specialty parotta filled with spiced, fluffy whisked eggs.',
    price: 40,
    category: 'parotta',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'p6',
    name: 'Egg Kuthu Parotta',
    description: 'Shredded parotta chopped on a flat griddle and wok-tossed with fresh eggs, onions, and flavorful salna.',
    price: 110,
    category: 'parotta',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'p7',
    name: 'Chicken Kuthu Parotta',
    description: 'A street-food legend: shredded parotta chopped with eggs, spiced chicken pieces, and hot chicken salna.',
    price: 140,
    category: 'parotta',
    isVeg: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'p8',
    name: 'Veg Kuthu Parotta',
    description: 'Finely shredded parotta tossed on a griddle with mixed garden vegetables and aromatic vegetable curry.',
    price: 100,
    category: 'parotta',
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'p9',
    name: 'Chilli Parotta',
    description: 'Crisp-shredded parotta chunks fried and tossed with capsicum, onions, and red-hot chili sauces.',
    price: 130,
    category: 'parotta',
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'p10',
    name: 'Chapatti (1 Set)',
    description: 'Soft and healthy whole wheat flatbreads cooked on a traditional tawa, served as a pair.',
    price: 40,
    category: 'parotta',
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=600&auto=format&fit=crop',
  },
  // Category 5: Dosai
  {
    id: 'd1',
    name: 'Plain Dosa',
    description: 'Crispy, thin fermented rice and lentil crepe served with sambar and fresh chutneys.',
    price: 40,
    category: 'dosa',
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'd2',
    name: 'Egg Dosa',
    description: 'A classic crispy dosa with a freshly cracked egg spread over it, seasoned with pepper and salt.',
    price: 60,
    category: 'dosa',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'd3',
    name: 'Kal Dosa',
    description: 'Soft, spongy, slightly thicker home-style dosa cooked on a traditional cast iron griddle.',
    price: 20,
    category: 'dosa',
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'd4',
    name: 'Ghee Dosa',
    description: 'Super thin and crispy paper dosa roasted beautifully with aromatic pure clarified butter (ghee).',
    price: 60,
    category: 'dosa',
    isVeg: true,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'd5',
    name: 'Podi Dosa',
    description: 'Deliciously crispy dosa coated with aromatic, spicy gun powder (podi) and pure ghee.',
    price: 50,
    category: 'dosa',
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'd6',
    name: 'Special Dosa',
    description: 'A chef special gold-standard crispy dosa served with a rich pairing of traditional curries.',
    price: 60,
    category: 'dosa',
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'd7',
    name: 'Chicken Kari Dosa',
    description: 'A Madurai specialty: thick rice pancake topped with spiced minced chicken, egg, onions, and curry leaves.',
    price: 100,
    category: 'dosa',
    isVeg: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'd8',
    name: 'Mutton Kari Dosa',
    description: 'The ultimate culinary indulgence - soft thick dosa layered with spicy minced mutton and cooked to perfection.',
    price: 130,
    category: 'dosa',
    isVeg: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=600&auto=format&fit=crop',
  },
  // Category 6: Omelette
  {
    id: 'o1',
    name: 'Onion Omelette',
    description: 'Classic double-egg omelette whisked with finely chopped onions, green chilies, and a dash of pepper.',
    price: 20,
    category: 'omelette',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'o2',
    name: 'Plain Omelette',
    description: 'Simple and comforting pan-fried double-egg omelette seasoned with salt and freshly ground black pepper.',
    price: 20,
    category: 'omelette',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'o3',
    name: 'Masala Omelette',
    description: 'Spicy Indian-style omelette filled with chopped onions, juicy tomatoes, fresh coriander, green chilies, and ground spices.',
    price: 30,
    category: 'omelette',
    isVeg: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'o4',
    name: 'Kalakki',
    description: 'A popular South Indian soft-scrambled egg delicacy, cooked with a splash of rich, flavorful chicken salna.',
    price: 20,
    category: 'omelette',
    isVeg: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'o5',
    name: 'Chicken Omelette',
    description: 'Gourmet egg omelette stuffed with seasoned shredded chicken, onions, coriander, and fine spices.',
    price: 50,
    category: 'omelette',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'o6',
    name: 'Egg Podimas',
    description: 'Traditional style scrambled eggs sautéed with onions, green chilies, curry leaves, and local spices.',
    price: 60,
    category: 'omelette',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'o7',
    name: 'Half Boiled',
    description: 'Perfectly pan-seared single-sided sunny up egg with a warm, runny yolk, sprinkled with freshly cracked pepper.',
    price: 20,
    category: 'omelette',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?q=80&w=600&auto=format&fit=crop',
  },
  // Category 7: TANDOORI & GRILL
  {
    id: 'tg1',
    name: 'Tandoori Chicken (Full)',
    description: 'Whole chicken marinated in yogurt, Kashmiri red chilies, and hand-ground spices, roasted in a clay tandoor.',
    price: 440,
    category: 'grill',
    isVeg: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'tg2',
    name: 'Tandoori Chicken (Half)',
    description: 'Half tender chicken marinated in spiked yogurt and grilled in a clay oven for authentic smokiness.',
    price: 230,
    category: 'grill',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'tg3',
    name: 'Tandoori Chicken (Quarter)',
    description: 'Quarter portion of chicken slow-roasted in the tandoor with vibrant spices and lemon garnish.',
    price: 120,
    category: 'grill',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'tg4',
    name: 'Grill Chicken (Full)',
    description: 'Whole chicken roasted on a spit grill, flavored with black pepper, garlic, and special Lebanese herbs.',
    price: 440,
    category: 'grill',
    isVeg: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1598103442097-8b743e2b902a?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'tg5',
    name: 'Grill Chicken (Half)',
    description: 'Spit-roasted half chicken marinated with Arabic spices and served with a garlic dip.',
    price: 230,
    category: 'grill',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1598103442097-8b743e2b902a?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'tg6',
    name: 'Grill Chicken (Quarter)',
    description: 'Spit-roasted quarter chicken leg/breast basted with lemon, butter, and regional spices.',
    price: 120,
    category: 'grill',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1598103442097-8b743e2b902a?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'tg7',
    name: 'BBQ Chicken (Full)',
    description: 'Whole chicken grilled on live charcoal, slathered with a sweet-smoky bar-b-q glaze.',
    price: 450,
    category: 'grill',
    isVeg: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'tg8',
    name: 'BBQ Chicken (Half)',
    description: 'Succulent half chicken grilled over charcoal with a delicious smoky BBQ finish.',
    price: 240,
    category: 'grill',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'tg9',
    name: 'BBQ Chicken (Quarter)',
    description: 'Juicy charcoal-grilled quarter chicken basted with smoky BBQ sauce.',
    price: 130,
    category: 'grill',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'tg10',
    name: 'Chicken Tikka (6 Pieces)',
    description: 'Boneless chicken cubes marinated in spiced yogurt and grilled to smoky perfection on skewers.',
    price: 180,
    category: 'grill',
    isVeg: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=600&auto=format&fit=crop',
  },
  // Category 8: VEG GRAVY & DRY
  {
    id: 'vg1',
    name: 'Chilli Gobi Dry',
    description: 'Crispy fried cauliflower florets tossed in a spicy, savory chili sauce with onions and bell peppers.',
    price: 120,
    category: 'veggravy',
    isVeg: true,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb49785?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'vg2',
    name: 'Chilli Gobi Gravy',
    description: 'Crispy fried cauliflower florets served in a rich, tangy, and spicy chili-garlic gravy.',
    price: 130,
    category: 'veggravy',
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb49785?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'vg3',
    name: 'Gobi Manchurian Dry',
    description: 'Cauliflower bites deep-fried and sautéed in a classic Indo-Chinese sweet, tangy, and slightly spicy sauce.',
    price: 120,
    category: 'veggravy',
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb49785?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'vg4',
    name: 'Gobi Manchurian Gravy',
    description: 'Fried cauliflower florets simmered in a thick, delicious Manchurian sauce flavored with garlic and ginger.',
    price: 130,
    category: 'veggravy',
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb49785?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'vg5',
    name: 'Chilli Mushroom Dry',
    description: 'Plump button mushrooms batter-fried and tossed with fresh chilies, green onions, and flavorful soy sauce.',
    price: 130,
    category: 'veggravy',
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'vg6',
    name: 'Chilli Mushroom Gravy',
    description: 'Batter-fried juicy mushrooms coated in a rich, spicy, and glossy Indo-Chinese chili gravy.',
    price: 140,
    category: 'veggravy',
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'vg7',
    name: 'Mushroom Manchurian Dry',
    description: 'Fresh mushrooms battered, fried, and coated with a perfect sweet, sour, and spicy ginger-garlic sauce.',
    price: 130,
    category: 'veggravy',
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'vg8',
    name: 'Mushroom Manchurian Gravy',
    description: 'Golden fried mushrooms immersed in an aromatic soy-chili based thick Manchurian gravy.',
    price: 140,
    category: 'veggravy',
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'vg9',
    name: 'Chilli Paneer Dry',
    description: 'Cottage cheese chunks tossed with fresh bell peppers, onions, and green chilies in a spicy soy glaze.',
    price: 150,
    category: 'veggravy',
    isVeg: true,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'vg10',
    name: 'Chilli Paneer Gravy',
    description: 'Fried paneer cubes cooked in a vibrant, savory, and spicy chili sauce with thick gravy.',
    price: 170,
    category: 'veggravy',
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'vg11',
    name: 'Paneer Manchurian Dry',
    description: 'Deep-fried cottage cheese tossed with spring onions and a thick, tangy ginger-garlic Manchurian glaze.',
    price: 150,
    category: 'veggravy',
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'vg12',
    name: 'Paneer Manchurian Gravy',
    description: 'Paneer chunks fried and simmered in a rich, spicy, and tangy soy-based Manchurian gravy.',
    price: 170,
    category: 'veggravy',
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'vg13',
    name: 'Paneer Masala',
    description: 'Cottage cheese cooked in a spicy onion-tomato gravy with aromatic traditional Indian spices.',
    price: 140,
    category: 'veggravy',
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'vg14',
    name: 'Paneer Butter Masala',
    description: 'Rich, creamy, and mildly sweet gravy cooked with paneer chunks, butter, fresh cream, and a blend of spices.',
    price: 160,
    category: 'veggravy',
    isVeg: true,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=600&auto=format&fit=crop',
  },
  // Category 9: SEAFOOD STARTERS
  {
    id: 'sf1',
    name: 'Ahlla Fish Fry (1 Piece)',
    description: 'Traditional spice-marinated fish slice pan-fried to crispy golden perfection.',
    price: 70,
    category: 'seafood',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'sf2',
    name: 'Nethili Fish Fry (1 Plate)',
    description: 'Crispy, crunchy deep-fried anchovies tossed with aromatic curry leaves and fresh local spices.',
    price: 190,
    category: 'seafood',
    isVeg: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'sf3',
    name: 'Chilli Fish Dry',
    description: 'Stir-fried batter-coated fish chunks tossed in a sweet-spicy chili-garlic soy sauce with bell peppers.',
    price: 180,
    category: 'seafood',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'sf4',
    name: 'Chilli Fish Gravy',
    description: 'Succulent fried fish bites cooked in a vibrant, savory, and spicy chili sauce with a rich gravy.',
    price: 190,
    category: 'seafood',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'sf5',
    name: 'Fish Manchurian Dry',
    description: 'Deep-fried fish chunks tossed with fresh spring onions and an Indo-Chinese sweet-tangy ginger glaze.',
    price: 180,
    category: 'seafood',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'sf6',
    name: 'Fish Manchurian Gravy',
    description: 'Golden fried fish chunks simmered in a dark, thick, and flavorful ginger-garlic Manchurian gravy.',
    price: 190,
    category: 'seafood',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'sf7',
    name: 'Fish Masala',
    description: 'Tender fish pieces simmered in a traditional, highly seasoned tomato-onion curry gravy.',
    price: 170,
    category: 'seafood',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'sf8',
    name: 'Chettinadu Fish Masala',
    description: 'A fiery, aromatic fish dish cooked in a fresh, roasted Chettinad spice paste with rich coconut extracts.',
    price: 180,
    category: 'seafood',
    isVeg: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'sf9',
    name: 'Prawns 65',
    description: 'Crispy, deep-fried spicy prawns marinated in ginger, garlic, red chili, and local ground masalas.',
    price: 180,
    category: 'seafood',
    isVeg: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1559737632-15f577717462?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'sf10',
    name: 'Prawns Masala',
    description: 'Juicy prawns sautéed and cooked in a semi-thick spicy masala paste made with fresh tomatoes and herbs.',
    price: 170,
    category: 'seafood',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1559737632-15f577717462?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'sf11',
    name: 'Chettinadu Prawns',
    description: 'Flavorful prawns slow-cooked in a robust, freshly roasted Chettinad spice masala with a hint of pepper.',
    price: 180,
    category: 'seafood',
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1559737632-15f577717462?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'sf12',
    name: 'Prawns Pepper Fry',
    description: 'Delicious dry-style prawns sautéed with chopped onions, green chilies, and a heavy dose of crushed black pepper.',
    price: 190,
    category: 'seafood',
    isVeg: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1559737632-15f577717462?q=80&w=600&auto=format&fit=crop',
  }
];

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: 'g1',
    title: 'Signature Mutton Biriyani Pot',
    category: 'dishes',
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'g2',
    title: 'Clay-oven Tandoori Platter',
    category: 'dishes',
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'g3',
    title: 'Our Family Dining Ambience',
    category: 'ambience',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'g4',
    title: 'Freshly Baked Naan Bread',
    category: 'dishes',
    image: 'https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'g5',
    title: 'Premium Double Dining Setup',
    category: 'ambience',
    image: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'g6',
    title: 'Fragrant Basmati Chicken Biriyani',
    category: 'dishes',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't1',
    name: 'Suresh Kumar',
    rating: 5,
    text: 'Undoubtedly the best biriyani in Singaperumal Koil! The Mutton Biriyani was cooked to perfection - aromatic rice and tender mutton pieces. Truly premium authentic taste.',
    date: 'July 2, 2026',
  },
  {
    id: 't2',
    name: 'Deepika Raman',
    rating: 5,
    text: 'A clean family restaurant with excellent service. Their Elaneer Payasam is a absolute heavenly end to their spicy Chicken 65 and Biriyani combo. Highly recommended!',
    date: 'June 28, 2026',
  },
  {
    id: 't3',
    name: 'Arun Prasath (Local Guide)',
    rating: 5,
    text: 'Located right near the NH, very easy to access. The Seeraga Samba chicken biriyani reminds me of real home-style cooking with traditional masala blends. Perfect portions.',
    date: 'May 15, 2026',
  },
  {
    id: 't4',
    name: 'Ramesh Krishnan',
    rating: 5,
    text: 'Their Tandoori Chicken Tikka and special BBQ grill are out of this world! Very juicy, perfectly cooked, and pairs amazingly well with the fresh Butter Naan.',
    date: 'April 10, 2026',
  },
  {
    id: 't5',
    name: 'Meena Subramaniam',
    rating: 5,
    text: 'We order Al Alif Biriyani on WhatsApp for all our family get-togethers. The customer support is lightning fast, the food packaging is premium, and the taste is consistent.',
    date: 'March 29, 2026',
  },
  {
    id: 't6',
    name: 'Dr. Vignesh Chander',
    rating: 5,
    text: 'If you want premium luxury dine-in feel with realistic pricing and outstanding food quality, Hotel Al Alif is the absolute gold standard in this region. 10/10 stars.',
    date: 'February 14, 2026',
  },
];
